import React, { useEffect, useState } from "react";
import SEOPageLayout from "@/components/seo/SEOPageLayout";
const F = ({ q, a }) => { const [o, s] = useState(false); return <div className="border-b border-white/8"><button onClick={() => s(!o)} className="w-full flex items-start justify-between gap-4 py-4 text-left"><span className="text-white font-semibold text-[14px] leading-snug">{q}</span><span className="text-[#B8860B] text-lg shrink-0">{o ? "−" : "+"}</span></button>{o && <p className="text-white/55 text-[13px] leading-relaxed pb-4 pr-8">{a}</p>}</div>; };
export default function BestOkirikaSupplier() {
  useEffect(() => { document.title = "Best Okirika Supplier in Nigeria | Kay Amazing Grace Global Aba"; const m = document.querySelector('meta[name="description"]'); if (m) m.setAttribute("content", "Find the best okirika supplier in Nigeria. Kay Amazing Grace Global in Aba supplies Grade A thrift bales to resellers nationwide. Trusted, reliable, quality guaranteed. WhatsApp 08035239489."); }, []);
  return (
    <SEOPageLayout breadcrumb="Best Okirika Supplier" category="SEO" h1="Best Okirika Supplier in Nigeria — Kay Amazing Grace Global, Aba">
      <p className="text-white/70 text-[15px] leading-relaxed mb-6">Choosing the <strong className="text-white">best okirika supplier in Nigeria</strong> makes the difference between a thriving bale business and a frustrating one. At Kay Amazing Grace Global, we have built our reputation on three pillars: Grade A quality, transparent pricing, and reliable nationwide delivery — all from our base on Ngwa Road, Aba.</p>
      <h2 className="text-white font-bold text-xl mt-8 mb-3">What Sets Kay Amazing Grace Global Apart</h2>
      <ul className="text-white/70 text-[14px] leading-relaxed mb-6 space-y-2 list-none">{["Grade A quality only — no compromises on bale standards","Photos and video before every single order — zero surprises","Physical address in Aba — verifiable and walk-in friendly","Hundreds of satisfied buyers across Nigeria","Nationwide delivery to all 36 states","Fast WhatsApp responses — we don't leave buyers waiting","Honest pricing — no hidden charges"].map(i=><li key={i} className="flex items-start gap-2"><span className="text-[#B8860B] mt-1">▸</span><span>{i}</span></li>)}</ul>
      <h2 className="text-white font-bold text-xl mt-8 mb-3">How to Spot a Good Okirika Supplier</h2>
      <p className="text-white/70 text-[14px] leading-relaxed mb-4">A reliable okirika supplier will: show you photos before payment; have a traceable physical address; be responsive on WhatsApp or phone; offer Grade A quality; and have a track record of successful deliveries. Be cautious of suppliers who ask for full payment before showing any photos of available stock.</p>
      <h2 className="text-white font-bold text-xl mt-8 mb-3">FAQs</h2>
      <div className="mt-4 mb-8">{[{q:"Who is considered the best okirika supplier in Nigeria?",a:"Kay Amazing Grace Global on Ngwa Road, Aba is one of the most consistently recommended okirika suppliers in Nigeria for Grade A quality and nationwide delivery."},{q:"How do I verify an okirika supplier is legitimate?",a:"Check that they have a physical address, will send photos before payment, are reachable consistently on WhatsApp or phone, and have verifiable customer reviews."},{q:"Can I test with one bale before buying in bulk?",a:"Yes. We welcome first-time buyers with single bale orders. Once you are satisfied with quality, you can scale up. WhatsApp 08035239489 to start."}].map((f,i)=><F key={i} {...f}/>)}</div>
    </SEOPageLayout>
  );
}