import React, { useEffect, useState } from "react";
import SEOPageLayout from "@/components/seo/SEOPageLayout";
const F = ({ q, a }) => { const [o, s] = useState(false); return <div className="border-b border-white/8"><button onClick={() => s(!o)} className="w-full flex items-start justify-between gap-4 py-4 text-left"><span className="text-white font-semibold text-[14px] leading-snug">{q}</span><span className="text-[#B8860B] text-lg shrink-0">{o ? "−" : "+"}</span></button>{o && <p className="text-white/55 text-[13px] leading-relaxed pb-4 pr-8">{a}</p>}</div>; };
export default function GradeAOkirikaNigeria() {
  useEffect(() => { document.title = "Grade A Okirika Nigeria | Highest Quality Thrift Bales — Kay Amazing Grace Global Aba"; const m = document.querySelector('meta[name="description"]'); if (m) m.setAttribute("content", "Buy Grade A okirika bales in Nigeria from Kay Amazing Grace Global, Aba. The highest quality second-hand clothing bales for resellers and boutiques. WhatsApp 08035239489."); }, []);
  return (
    <SEOPageLayout breadcrumb="Grade A Okirika Nigeria" category="SEO" h1="Grade A Okirika Nigeria — Highest Quality Bales from Aba">
      <p className="text-white/70 text-[15px] leading-relaxed mb-6">In Nigeria's okirika market, Grade A is the gold standard. <strong className="text-white">Kay Amazing Grace Global</strong> in Aba supplies exclusively Grade A okirika bales — the highest quality category of second-hand clothing — ensuring resellers and boutique owners receive stock that meets their customers' expectations and commands top resale prices.</p>
      <h2 className="text-white font-bold text-xl mt-8 mb-3">What is Grade A Okirika?</h2>
      <p className="text-white/70 text-[14px] leading-relaxed mb-4">Grade A is the top tier of the okirika grading system. Grade A items are in excellent to near-new condition — minimal wear, no tears, rips, significant staining, or major damage. Grade A bales often contain items with original price tags still attached. They are the most profitable to resell because customers accept higher prices for clearly quality items.</p>
      <h2 className="text-white font-bold text-xl mt-8 mb-3">Grade A vs Lower Grade Okirika</h2>
      <div className="overflow-x-auto mb-6"><table className="w-full text-[13px] border border-white/10"><thead><tr className="bg-white/5"><th className="text-left px-4 py-2 text-white/70 font-bold border-b border-white/10">Feature</th><th className="text-left px-4 py-2 text-[#B8860B] font-bold border-b border-white/10">Grade A</th><th className="text-left px-4 py-2 text-white/70 font-bold border-b border-white/10">Lower Grade</th></tr></thead><tbody>{[["Condition","Excellent / near-new","Worn, some damage"],["Customer Satisfaction","High","Variable"],["Resale Price","Higher","Lower"],["Returns/Complaints","Rare","More common"],["Profit Margin","Better long-term","Lower quality = lower price"]].map(([f,a,b])=><tr key={f} className="border-b border-white/5"><td className="px-4 py-2 text-white/60">{f}</td><td className="px-4 py-2 text-[#B8860B]">{a}</td><td className="px-4 py-2 text-white/60">{b}</td></tr>)}</tbody></table></div>
      <h2 className="text-white font-bold text-xl mt-8 mb-3">FAQs</h2>
      <div className="mt-4 mb-8">{[{q:"What does Grade A mean in okirika?",a:"Grade A means the highest quality level — clothing in excellent or near-new condition with minimal wear and no significant damage."},{q:"Why should I only buy Grade A okirika?",a:"Grade A okirika yields higher resale prices, fewer customer complaints, better repeat business, and stronger profit margins over time."},{q:"Does Kay Amazing Grace Global only sell Grade A?",a:"Yes. We only supply Grade A quality bales. We inspect all stock at our Aba warehouse before sale."}].map((f,i)=><F key={i} {...f}/>)}</div>
    </SEOPageLayout>
  );
}