import React, { useEffect, useState } from "react";
import SEOPageLayout from "@/components/seo/SEOPageLayout";
const F = ({ q, a }) => { const [o, s] = useState(false); return <div className="border-b border-white/8"><button onClick={() => s(!o)} className="w-full flex items-start justify-between gap-4 py-4 text-left"><span className="text-white font-semibold text-[14px] leading-snug">{q}</span><span className="text-[#B8860B] text-lg shrink-0">{o ? "−" : "+"}</span></button>{o && <p className="text-white/55 text-[13px] leading-relaxed pb-4 pr-8">{a}</p>}</div>; };
export default function OkirikaResellerNigeria() {
  useEffect(() => { document.title = "Okirika Reseller Nigeria | Start Your Bale Business — Kay Amazing Grace Global Aba"; const m = document.querySelector('meta[name="description"]'); if (m) m.setAttribute("content", "Want to become an okirika reseller in Nigeria? Kay Amazing Grace Global in Aba supplies Grade A bales for new and experienced resellers. WhatsApp 08035239489 to get started."); }, []);
  return (
    <SEOPageLayout breadcrumb="Okirika Reseller Nigeria" category="SEO" h1="Okirika Reseller Nigeria — Start Your Bale Business with Kay Amazing Grace Global">
      <p className="text-white/70 text-[15px] leading-relaxed mb-6">Okirika reselling is one of Nigeria's most accessible and profitable small businesses. Whether you are just starting out or looking to grow your existing bale business, <strong className="text-white">Kay Amazing Grace Global</strong> in Aba is ready to be your wholesale supplier. We support new resellers from their very first bale order.</p>
      <h2 className="text-white font-bold text-xl mt-8 mb-3">How to Start as an Okirika Reseller</h2>
      <ol className="text-white/70 text-[14px] leading-relaxed mb-6 space-y-2">{["Decide on your market — open market, boutique, or online (WhatsApp/Instagram)","Choose a starting bale category based on your customer base","Set your starting capital (minimum 1 bale order with us)","WhatsApp 08035239489 for bale recommendations for your specific situation","Receive your first bale, open it, sort it, and start selling","Reinvest your profits to grow your bale order over time"].map((s,i)=><li key={i} className="flex items-start gap-3 list-none"><span className="text-[#B8860B] font-bold shrink-0">{i+1}.</span><span>{s}</span></li>)}</ol>
      <h2 className="text-white font-bold text-xl mt-8 mb-3">Best Bale Types for New Resellers</h2>
      <p className="text-white/70 text-[14px] leading-relaxed mb-4">Mixed bales are the most recommended starting point — variety helps you discover what sells in your specific market. Ladies wear bales are also strong performers for resellers in any location. Start with one bale, learn, and then scale.</p>
      <h2 className="text-white font-bold text-xl mt-8 mb-3">FAQs</h2>
      <div className="mt-4 mb-8">{[{q:"Can I start as an okirika reseller with little capital?",a:"Yes. Minimum order at Kay Amazing Grace Global is 1 bale. We guide new resellers through their first order. WhatsApp 08035239489 to discuss options for your budget."},{q:"What is the most profitable okirika category for resellers?",a:"Ladies wear and Korea bales consistently deliver the highest profit margins. Mixed bales are best for beginners exploring different categories."},{q:"Do you mentor new okirika resellers?",a:"We guide every new buyer through the ordering and selling process. WhatsApp 08035239489 — we are friendly and patient with first-time buyers."}].map((f,i)=><F key={i} {...f}/>)}</div>
    </SEOPageLayout>
  );
}